# Generated by Django 4.1.3 on 2022-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
