# Generated by Django 4.1.3 on 2022-12-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airport_trip_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.airport'),
        ),
    ]
