# Generated by Django 4.1.3 on 2023-01-01 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hotel_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmailForAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport', to=settings.AUTH_USER_MODEL),
        ),
    ]
