from .UserRegisterSerializer import *
from .UserDetailsSerializer import *
from .AirportSerializer import *
from .SeatSerializer import *
from .TripSerializer import *
from .CommentSerializer import *
from .RecommendationsSerializer import *
from .AllowedEmailForAirportSerializer import *
from .AirportRegisterSerializer import *
from .UpdateBalanceSerializer import *
